language: java
jdk: 
  - openjdk11
  
addons:
  sonarcloud:
    organization: 404notfoundpk
    token: 5dbdb4ea476c99be6729425eda07642b47b4b539
 
script:
  - mvn clean verify -e org.jacoco:jacoco-maven-plugin:prepare-agent sonar:sonar -Dsonar.projectKey=404notfoundpk_ISW2-DELIVERABLE1
